name: srvey
channels:
  - conda-forge
  - defaults
dependencies:
  ## Core
  - python>=3.10
  - pytorch::pytorch>=1.10
  # - pytorch/win-64::torchvision>=0.10=py39_cu111 # my-hardware specific bug(?)
  - pytorch::torchvision>=0.11
  - nvidia::cudatoolkit=11.3.1
  - comet_ml::comet_ml
  - matplotlib
  - numpy
  - verde
  ## geophys_utils
  # - numexpr
  # - affine
  # - netCDF4
  # - gdal
  # - owslib
  # - scikit-image
  # - scipy
  # - cartopy
  # - shapely
  ## Quality of life
  - black
  - colorcet
  - flake8
  - jupyter
  - ipykernel
  - nb_conda
  - tqdm
  - rope

# Enable strict channel priority!
# conda config --set channel_priority strict